/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Websocket_protocols = sequelize.define('Websocket_protocols', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    type: DataTypes.STRING(254),
    hash: DataTypes.STRING(254),
  }, {
      tableName: 'Person',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return Websocket_protocols;
  };