/**
   * Created by Bruno Costa 2023-03-10
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Access = sequelize.define('Access', {
      id: {
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      user_id: {
        type: DataTypes.INTEGER(11),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      accessOn: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      ipv4: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      ipv6: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      platform: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      valid: {
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      revokedOn: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      city: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      country: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      accessToken: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Access',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
              Access.belongsTo(models.User, {
                foreignKey: 'user_id',              //on Access
                targetKey: 'id',  //foreign key
              });
        }
      },
    });

    return Access;
  };