/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Annotation = sequelize.define('Annotation', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    mature_miRNA_id: DataTypes.INTEGER(11),
    date: DataTypes.DATE,
    version: DataTypes.INTEGER(11),
    assay_data_id: DataTypes.INTEGER(11),
  }, {
      tableName: 'Annotation',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Annotation.belongsTo(models.Mature_miRNA, {
            foreignKey: 'mature_miRNA_id',              //on Annotation
            targetKey: 'id',  //foreign key  
          });
          Annotation.belongsTo(models.Assay_data, {
            foreignKey: 'assay_data_id',              //on Annotation
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });
    return Annotation;
  };