/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Annotation = sequelize.define('Annotation', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      mature_miRNA_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      date: { 
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      version: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      assay_data_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Annotation',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Annotation.belongsTo(models.Mature_miRNA, {
            foreignKey: 'mature_miRNA_id',              //on Annotation
            targetKey: 'id',  //foreign key  
          });
          Annotation.belongsTo(models.Assay_data, {
            foreignKey: 'assay_data_id',              //on Annotation
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Annotation;
  };