/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Assay_Modality = sequelize.define('Assay_Modality', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    assay_id: DataTypes.INTEGER(11),
    modality_id: DataTypes.INTEGER(11),
  }, {
      tableName: 'Assay_Modality',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Assay_Modality.belongsTo(models.Assay, {
            foreignKey: 'assay_id',              //on Assay_Modality
            targetKey: 'id',  //foreign key  
          });
          Assay_Modality.belongsTo(models.Modality, {
            foreignKey: 'modlity_id',              //on Assay_Modality
            targetKey: 'id',  //foreign key  
          });
        }
      },
    });

    return Assay_Modality;
  };