/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Assay_data = sequelize.define('Assay_data', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    assay: DataTypes.INTEGER(11),
    raw: DataTypes.INTEGER(11),
    cpm: DataTypes.FLOAT,
  }, {
      tableName: 'Assay_data',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Assay_data.belongsTo(models.Assay, {
            foreignKey: 'assay',              //on Assay_data
            targetKey: 'id',  //foreign key  
          }); 
          Assay_data.belongsTo(models.Annotation, {
            foreignKey: 'id',              //on Assay_data
            targetKey: 'assay_data_id',  //foreign key  
          }); 
        }
      },
    });

    return Assay_data;
  };