/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Assay = sequelize.define('Assay', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(255),
    study: DataTypes.INTEGER(11),
    sample: DataTypes.INTEGER(11),
    operation: DataTypes.STRING,
    type: DataTypes.STRING(254),
    output: DataTypes.INTEGER(11),
  }, {
      tableName: 'Assay',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Assay.belongsTo(models.Study, {
            foreignKey: 'study',              //on Assay
            targetKey: 'id',  //foreign key  
          });
          Assay.belongsTo(models.Sample, {
            foreignKey: 'sample',              //on Assay
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Assay;
  };