/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Differential_expression = sequelize.define('Differential_expression', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    logCPM: DataTypes.FLOAT,
    fTest: DataTypes.FLOAT,
    logFC: DataTypes.FLOAT,
    pValue: DataTypes.FLOAT,
    fdr: DataTypes.FLOAT,
    study: DataTypes.INTEGER(11),
    modality1: DataTypes.INTEGER(11),
    modality2: DataTypes.INTEGER(11),
    sequence: DataTypes.INTEGER(11),
  }, {
      tableName: 'Differential_expression',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Differential_expression.belongsTo(models.Study, {
            foreignKey: 'study',              //on Differential_expression
            targetKey: 'id',  //foreign key  
          });
          Differential_expression.belongsTo(models.Modality, {
            foreignKey: 'modality1',              //on Differential_expression
            targetKey: 'id',  //foreign key  
          });
          Differential_expression.belongsTo(models.Modality, {
            foreignKey: 'modality2',              //on Differential_expression
            targetKey: 'id',  //foreign key  
          });
          Differential_expression.belongsTo(models.Mature_miRNA_sequence, {
            foreignKey: 'sequence',              //on Differential_expression
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Differential_expression;
  };