/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Factor = sequelize.define('Factor', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      name: { 
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Factor',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Factor.belongsTo(models.Modality, {
            foreignKey: 'id',              //on Factor
            targetKey: 'factor_id',  //foreign key  
          }); 
        }
      },
    });

    return Factor;
  };