/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Factor = sequelize.define('Factor', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    name: DataTypes.STRING(254),
    assay_id: DataTypes.INTEGER(11),
  }, {
      tableName: 'Factor',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Factor.belongsTo(models.Assay, {
            foreignKey: 'assay_id',              //on Factor
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Factor;
  };