/**
 * Created by Bruno Costa 28-04-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Feature = sequelize.define('Feature', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    genome_id: DataTypes.INTEGER(11),
    name: DataTypes.STRING(254),
    source: DataTypes.STRING(254),
    type: DataTypes.STRING(254),
    start: DataTypes.INTEGER(254),
    end: DataTypes.INTEGER(254),
    score: DataTypes.FLOAT,
    strand: DataTypes.STRING(1),
    phase: DataTypes.INTEGER(1),
    attribute_list: DataTypes.STRING(254),
    attr_id: DataTypes.STRING(254),
  }, {
    tableName: 'Feature',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Feature.belongsTo(models.Genome, {
          foreignKey: 'genome_id',              //on Feature
          targetKey: 'id',  //foreign key  
        });
        Feature.belongsTo(models.Gene, {
          foreignKey: 'id',              //on Feature
          targetKey: 'feature_id',  //foreign key  
        });
        Feature.belongsTo(models.Pre_miRNA, {
          foreignKey: 'id',              //on Feature
          targetKey: 'feature_id',  //foreign key  
        }); 
      }
    },
  });

  return Feature;
};
