/**
 * Created by Bruno Costa 2023-03-25
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Feature_composite = sequelize.define('Feature_composite', {
    id: {
      type: DataTypes.INTEGER(11),
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
    accession: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: true,
      allowNull: false
    },
    name: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    source: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    type: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    start: {
      type: DataTypes.INTEGER(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    end: {
      type: DataTypes.INTEGER(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    score: {
      type: DataTypes.FLOAT,
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
    strand: {
      type: DataTypes.STRING(1),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    phase: {
      type: DataTypes.INTEGER(1),
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
    sequence_assembly_key: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    sequence_assembly_value: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    composite: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
  }, {
    tableName: 'Feature_composite',
    timestamps: false,
    underscored: false,

    classMethods: {
      associate: function associate(models) {

        Feature_composite.belongsTo(models.Mature_miRNA, {
          foreignKey: 'accession',              //on Feature_composite
          targetKey: 'accession',  //foreign key
        });
        Feature_composite.belongsTo(models.Sequence_assembly_composite, {
          foreignKey: 'composite',              //on Feature_composite
          targetKey: 'composite',  //foreign key
        });
        Feature_composite.belongsTo(models.Pre_miRNA, {
          foreignKey: 'accession',              //on Feature_composite
          targetKey: 'accession',  //foreign key
        });
/*        Feature_composite.belongsTo(models.Messenger_RNA, {
          foreignKey: 'accession',              //on Feature_composite
          targetKey: 'accession',  //foreign key
        });*/
      }
    },
  });

  return Feature_composite;
};