/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Feature_attribute_list = sequelize.define('Feature_attribute_list', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    feature_id: DataTypes.INTEGER(11),
    key: DataTypes.STRING(254),
    value: DataTypes.STRING(254),
  }, {
      tableName: 'Feature_attribute_list',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Feature_attribute_list.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Feature_attribute_list
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Feature_attribute_list;
  };