/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Gene = sequelize.define('Gene', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      feature_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      accession: { 
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Gene',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Gene.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Gene
            targetKey: 'id',  //foreign key  
          });
          Gene.belongsTo(models.Protein, {
            foreignKey: 'id',              //on Gene
            targetKey: 'gene_id',  //foreign key  
          }); 
        }
      },
    });

    return Gene;
  };