/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Gene = sequelize.define('Gene', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    feature_id: DataTypes.INTEGER(11),
    protein_id: DataTypes.INTEGER(11),
  }, {
      tableName: 'Gene',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Gene.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Gene
            targetKey: 'id',  //foreign key  
          });
          Gene.belongsTo(models.Protein, {
            foreignKey: 'id',              //on Gene
            targetKey: 'gene_id',  //foreign key  
          });
          Gene.belongsTo(models.Transcript, {
            foreignKey: 'id',              //on Gene
            targetKey: 'gene_id',  //foreign key  
          }); 
        }
      },
    });

    return Gene;
  };