/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Genome = sequelize.define('Genome', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    organism_id: DataTypes.INTEGER(11),
    assembly: DataTypes.STRING(254),
    external_id: DataTypes.STRING(254),
    project: DataTypes.STRING(254),
    genome_build: DataTypes.STRING(254),
  }, {
      tableName: 'Genome',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Genome.belongsTo(models.Feature, {
            foreignKey: 'id',              //on Genome
            targetKey: 'genome_id',  //foreign key  
          });
          Genome.belongsTo(models.Organism, {
            foreignKey: 'organism_id',              //on Genome
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Genome;
  };