/**
 * Created by Bruno Costa 28-04-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Genome = sequelize.define('Genome', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    genus: DataTypes.STRING(254),
    species: DataTypes.STRING(254),
    ncbi_taxon_id: DataTypes.STRING(254),
    assembly: DataTypes.STRING(254),
    external_id: DataTypes.STRING(254),
    organism_id: DataTypes.INTEGER(11),
    abbreviation: DataTypes.STRING(3),
  }, {
    tableName: 'Genome',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Genome.belongsTo(models.Feature, {
          foreignKey: 'id',              //on Genome
          targetKey: 'genome_id',  //foreign key  
        });
        Genome.belongsTo(models.Organism, {
          foreignKey: 'organism_id',              //on Genome
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return Genome;
};
