/**
   * Created by Bruno Costa 2023-03-10
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Has_user_with_role = sequelize.define('Has_user_with_role', {
      id: {
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      role: {
        type: DataTypes.ENUM('admin','curator','researcher'),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      person: {
        type: DataTypes.INTEGER(11),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      user: {
        type: DataTypes.INTEGER(11),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Has_user_with_role',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
              Has_user_with_role.belongsTo(models.Person, {
                foreignKey: 'person',              //on Has_user_with_role
                targetKey: 'id',  //foreign key
              });
              Has_user_with_role.belongsTo(models.User, {
                foreignKey: 'user',              //on Has_user_with_role
                targetKey: 'id',  //foreign key
              });
        }
      },
    });

    return Has_user_with_role;
  };