/**
 * Created by Bruno Costa 28-04-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const HasStar = sequelize.define('HasStar', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    miRNA_id: DataTypes.INTEGER(11),
    star_miRNA_id: DataTypes.INTEGER(11),
  }, {
    tableName: 'HasStar',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        HasStar.belongsTo(models.Mature_miRNA, {
          foreignKey: 'miRNA_id',              //on HasStar
          targetKey: 'id',  //foreign key  
        });
        HasStar.belongsTo(models.Mature_miRNA, {
          foreignKey: 'star_miRNA_id',              //on HasStar
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return HasStar;
};
