/**
   * Created by Bruno Costa 2023-03-20
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Managed_by = sequelize.define('Managed_by', {
      id: {
        type: DataTypes.INTEGER(10),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      study: {
        type: DataTypes.INTEGER(10),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      person: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      scope: {
        type: DataTypes.ENUM('creator','curator','editor'),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Managed_by',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
              Managed_by.belongsTo(models.Person, {
                foreignKey: 'person',              //on Managed_by
                targetKey: 'email',  //foreign key
              });
              Managed_by.belongsTo(models.Study, {
                foreignKey: 'study',              //on Managed_by
                targetKey: 'id',  //foreign key
              });
        }
      },
    });

    return Managed_by;
  };