/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Mature_has_Pre = sequelize.define('Mature_has_Pre', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      mature_miRNA_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      pre_miRNA_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Mature_has_Pre',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Mature_has_Pre.belongsTo(models.Mature_miRNA, {
            foreignKey: 'mature_miRNA_id',              //on Mature_has_Pre
            targetKey: 'id',  //foreign key  
          });
          Mature_has_Pre.belongsTo(models.Pre_miRNA, {
            foreignKey: 'pre_miRNA_id',              //on Mature_has_Pre
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Mature_has_Pre;
  };