/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Mature_has_Pre = sequelize.define('Mature_has_Pre', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    mature_miRNA_id: DataTypes.INTEGER(20),
    pre_miRNA_id: DataTypes.INTEGER(20),
    feature_id: DataTypes.INTEGER(20),
  }, {
      tableName: 'Mature_has_Pre',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Mature_has_Pre.belongsTo(models.Mature_miRNA, {
            foreignKey: 'mature_miRNA_id',              //on Mature_has_Pre
            targetKey: 'id',  //foreign key  
          });
          Mature_has_Pre.belongsTo(models.Pre_miRNA, {
            foreignKey: 'pre_miRNA_id',              //on Mature_has_Pre
            targetKey: 'id',  //foreign key  
          });
          Mature_has_Pre.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Mature_has_Pre
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Mature_has_Pre;
  };