/**
 * Created by Bruno Costa 28-04-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Mature_miRNA = sequelize.define('Mature_miRNA', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    accession: DataTypes.STRING(254),
    name: DataTypes.STRING(254),
    description: DataTypes.STRING(254),
    arm: DataTypes.STRING(254),
    sequence: DataTypes.STRING(254),
  }, {
    tableName: 'Mature_miRNA',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Mature_miRNA.belongsTo(models.HasStar, {
          foreignKey: 'id',              //on Mature_miRNA
          targetKey: 'miRNA_id',  //foreign key  
        });
        Mature_miRNA.belongsTo(models.HasStar, {
          foreignKey: 'id',              //on Mature_miRNA
          targetKey: 'star_miRNA_id',  //foreign key  
        });
        Mature_miRNA.belongsTo(models.Pre_miRNA, {
          foreignKey: 'id',              //on Mature_miRNA
          targetKey: 'mature_miRNA_id',  //foreign key  
        });
        Mature_miRNA.belongsTo(models.Target, {
          foreignKey: 'id',              //on Mature_miRNA
          targetKey: 'mature_miRNA_id',  //foreign key  
        }); 
      }
    },
  });

  return Mature_miRNA;
};
