/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Modality = sequelize.define('Modality', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      name: { 
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      factor_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Modality',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Modality.belongsTo(models.Assay_Modality, {
            foreignKey: 'id',              //on Modality
            targetKey: 'modality_id',  //foreign key  
          });
          Modality.belongsTo(models.Differential_expression, {
            foreignKey: 'id',              //on Modality
            targetKey: 'modality1',  //foreign key  
          });
          Modality.belongsTo(models.Differential_expression, {
            foreignKey: 'id',              //on Modality
            targetKey: 'modality2',  //foreign key  
          });
          Modality.belongsTo(models.Factor, {
            foreignKey: 'factor_id',              //on Modality
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Modality;
  };