/**
 * Created by Bruno Costa 2023-03-08
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Organism = sequelize.define('Organism', {
    ncbi_taxon_id: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: true,
      allowNull: false
    },
    abbreviation: {
      type: DataTypes.STRING(3),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    common_name: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
    genus: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: false
    },
    specific_name: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
    subspecific_name_key: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
    subspecific_name_value: {
      type: DataTypes.STRING(254),
      autoIncrement: false,
      primaryKey: false,
      allowNull: true
    },
  }, {
    tableName: 'Organism',
    timestamps: false,
    underscored: false,

    classMethods: {
      associate: function associate(models) {
        Organism.hasMany(models.Sequence_assembly_composite, {
          foreignKey: 'organism',              //on Organism
          targetKey: 'ncbi_taxon_id',  //foreign key
        });
      }
    },
  });

  return Organism;
};