/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Organism = sequelize.define('Organism', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    abbreviation: DataTypes.STRING(3),
    common_name: DataTypes.STRING(254),
    genus: DataTypes.STRING(254),
    species: DataTypes.STRING(254),
    sub_species: DataTypes.STRING(254),
    ncbi_taxon_id: DataTypes.STRING(254),
  }, {
      tableName: 'Organism',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Organism.belongsTo(models.Genome, {
            foreignKey: 'id',              //on Organism
            targetKey: 'organism_id',  //foreign key  
          });
          Organism.belongsTo(models.Transcript, {
            foreignKey: 'id',              //on Organism
            targetKey: 'organism_id',  //foreign key  
          }); 
        }
      },
    });

    return Organism;
  };