/**
   * Created by Bruno Costa 2023-03-20
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Person = sequelize.define('Person', {
      email: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      orcid: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      firstName: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      lastName: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      institutional_address: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
    }, {
      tableName: 'Person',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {
              Person.belongsTo(models.Managed_by, {
                foreignKey: 'email',              //on Person
                targetKey: 'person',  //foreign key
              });
              Person.belongsTo(models.User, {
                foreignKey: 'email',              //on Person
                targetKey: 'email',  //foreign key
              });
        }
      },
    });

    return Person;
  };