/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Person = sequelize.define('Person', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    firstName: DataTypes.STRING(254),
    lastName: DataTypes.STRING(254),
  }, {
      tableName: 'Person',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {
          Person.belongsTo(models.Study, {
            foreignKey: 'id',              //on Study
            targetKey: 'responsible',  //foreign key  
          });              
        }
      },
    });

    return Person;
  };