/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Pre_has_Feature = sequelize.define('Pre_has_Feature', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    pre_miRNA_id: DataTypes.INTEGER(20),
    feature_id: DataTypes.INTEGER(20),
  }, {
      tableName: 'Pre_has_Feature',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Pre_has_Feature.belongsTo(models.Pre_miRNA, {
            foreignKey: 'pre_miRNA_id',              //on Pre_has_Feature
            targetKey: 'id',  //foreign key  
          });
          Pre_has_Feature.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Pre_has_Feature
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Pre_has_Feature;
  };