/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Pre_has_Feature = sequelize.define('Pre_has_Feature', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      pre_miRNA_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      feature_id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Pre_has_Feature',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Pre_has_Feature.belongsTo(models.Pre_miRNA, {
            foreignKey: 'pre_miRNA_id',              //on Pre_has_Feature
            targetKey: 'id',  //foreign key  
          });
          Pre_has_Feature.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Pre_has_Feature
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Pre_has_Feature;
  };