/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Pre_miRNA = sequelize.define('Pre_miRNA', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    accession: DataTypes.STRING(254),
    name: DataTypes.STRING(254),
    description: DataTypes.STRING(254),
    feature_id: DataTypes.INTEGER(11),
    sequence_id: DataTypes.INTEGER(20),
  }, {
      tableName: 'Pre_miRNA',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Pre_miRNA.belongsTo(models.Mature_miRNA, {
            foreignKey: 'id',              //on Pre_miRNA
            targetKey: 'pre_miRNA_id',  //foreign key  
          });
          Pre_miRNA.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Pre_miRNA
            targetKey: 'id',  //foreign key  
          });
          Pre_miRNA.belongsTo(models.Pre_miRNA_sequence, {
            foreignKey: 'sequence_id',              //on Pre_miRNA
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Pre_miRNA;
  };