/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Profile = sequelize.define('Profile', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    type: DataTypes.STRING(254),
    profile: DataTypes.STRING(254),
    table: DataTypes.STRING(254),
    columnName: DataTypes.STRING(254),
    fileColumnIndex: DataTypes.INTEGER(20),
  }, {
      tableName: 'Profile',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {     
        }
      },
    });

    return Profile;
  };