/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Protein = sequelize.define('Protein', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    gene_id: DataTypes.INTEGER(11),
    protein_id: DataTypes.STRING(254),
    gi: DataTypes.STRING(254),
    name: DataTypes.STRING(254),
  }, {
      tableName: 'Protein',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Protein.belongsTo(models.Gene, {
            foreignKey: 'gene_id',              //on Protein
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Protein;
  };