/**
   * Created by Bruno Costa 2021-07-07
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Sample = sequelize.define('Sample', {
      id: { 
        type: DataTypes.INTEGER,
        autoIncrement: false,
        primaryKey: true,
        allowNull: false
      },
      Sample: { 
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      processed_by: { 
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Sample',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          Sample.belongsTo(models.Assay, {
            foreignKey: 'id',              //on Sample
            targetKey: 'sample',  //foreign key  
          }); 
        }
      },
    });

    return Sample;
  };