/**
   * Created by Bruno Costa 2023-03-20
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Study = sequelize.define('Study', {
      id: {
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: true
      },
      title: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      description: {
        type: DataTypes.TEXT,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      releaseDate: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      objective: {
        type: DataTypes.TEXT,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      active: {
        type: DataTypes.BOOLEAN,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true,
        defaultValue: false,
      },
      public: {
        type: DataTypes.BOOLEAN,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true,
        defaultValue: false,
      },
    }, {
      tableName: 'Study',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
              Study.hasMany(models.Assay, {
                foreignKey: 'study',              //on Study
                targetKey: 'id',  //foreign key
              });
              Study.belongsTo(models.Managed_by, {
                foreignKey: 'id',              //on Study
                targetKey: 'study',  //foreign key
              });
              Study.belongsTo(models.Target, {
                foreignKey: 'id',              //on Study
                targetKey: 'study_id',  //foreign key
              });
        }
      },
    });

    return Study;
  };