/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Study = sequelize.define('Study', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    title: DataTypes.STRING(254),
    responsible: {
      type:DataTypes.INTEGER(11),
      allowNull: true,
      defaultValue: null,
    },
    description: DataTypes.STRING,
    releaseDate: DataTypes.DATE,
    objective: DataTypes.STRING,
    active: DataTypes.BOOLEAN(1),
    public: DataTypes.BOOLEAN(1),
  }, {
      tableName: 'Study',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Study.belongsTo(models.Person, {
            foreignKey: 'responsible',              //on Study
            targetKey: 'id',  //foreign key  
          }); 
          Study.belongsTo(models.Target, {
            foreignKey: 'id',              //on Study
            targetKey: 'study_id',  //foreign key  
          }); 
          Study.belongsTo(models.Assay, {
            foreignKey: 'id',              //on Assay
            targetKey: 'study',  //foreign key  
          });
        }
      },
    });

    return Study;
  };