/**
   * Created by Bruno Costa 2023-03-16
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Table_access = sequelize.define('Table_access', {
      id: {
        type: DataTypes.INTEGER(100),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      name: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
    }, {
      tableName: 'Table_access',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
        }
      },
    });

    return Table_access;
  };