/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Target = sequelize.define('Target', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    mature_miRNA_id: DataTypes.INTEGER(11),
    transcript_id: DataTypes.INTEGER(11),
  }, {
      tableName: 'Target',
      timestamps: false,
      underscored: false,

     classMethods: {
        associate: function associate(models) {    
          Target.belongsTo(models.Mature_miRNA, {
            foreignKey: 'mature_miRNA_id',              //on Target
            targetKey: 'id',  //foreign key  
          });
          Target.belongsTo(models.Transcript, {
            foreignKey: 'transcript_id',              //on Target
            targetKey: 'id',  //foreign key  
          }); 
        }
      },
    });

    return Target;
  };