/**
 * Created by Bruno Costa 28-04-2018
 * Generated by Utilities/createTable.py
 */
'use strict';

module.exports = function(sequelize, DataTypes) {
  const Transcript = sequelize.define('Transcript', {
    id: { 
      type: DataTypes.INTEGER(11),
      autoIncrement: true,
      primaryKey: true,
      allowNull: false,
      unique: true,
    },
    organism_id: DataTypes.INTEGER(11),
    version: DataTypes.INTEGER(11),
    gene_id: DataTypes.INTEGER(11),
  }, {
    tableName: 'Transcript',
    timestamps: false,
    underscored: false,

   classMethods: {
      associate: function associate(models) {    
        Transcript.belongsTo(models.Target, {
          foreignKey: 'id',              //on Transcript
          targetKey: 'transcript_id',  //foreign key  
        });
        Transcript.belongsTo(models.Organism, {
          foreignKey: 'organism_id',              //on Transcript
          targetKey: 'id',  //foreign key  
        });
        Transcript.belongsTo(models.Gene, {
          foreignKey: 'gene_id',              //on Transcript
          targetKey: 'id',  //foreign key  
        }); 
      }
    },
  });

  return Transcript;
};
