/**
   * Created by Bruno Costa 28-04-2018
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const Transcript = sequelize.define('Transcript', {
      id: { 
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false,
        unique: true,
      },
    accession: DataTypes.STRING(254),
    version: DataTypes.INTEGER(11),
    feature_id: DataTypes.INTEGER(11),
  }, {
      tableName: 'Transcript',
      timestamps: false,
      underscored: false,
     classMethods: {
        associate: function associate(models) {    
          Transcript.belongsTo(models.Target, {
            foreignKey: 'id',              //on Transcript
            targetKey: 'transcript_id',  //foreign key  
          });
          Transcript.belongsTo(models.Feature, {
            foreignKey: 'feature_id',              //on Transcript
            targetKey: 'id',  //foreign key  
          }); 
          Transcript.belongsTo(models.Protein, {
            foreignKey: 'id',              //on Transcript
            targetKey: 'transcript_gene_id',  //foreign key  
          });
        }
      },
    });

    return Transcript;
  };