/**
   * Created by Bruno Costa 2023-03-10
   * Generated by Utilities/createTable.py
   */
  'use strict';

  module.exports = function(sequelize, DataTypes) {
    const User = sequelize.define('User', {
      id: {
        type: DataTypes.INTEGER(11),
        autoIncrement: true,
        primaryKey: true,
        allowNull: false
      },
      email: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      hash: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      createdOn: {
        type: DataTypes.DATE,
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      confirmationToken: {
        type: DataTypes.STRING(254),
        autoIncrement: false,
        primaryKey: false,
        allowNull: false
      },
      active: {
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      attempt: {
        type: DataTypes.INTEGER(5),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      ban: {
        type: DataTypes.TINYINT(1),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
      role: {
        type: DataTypes.ENUM('admin','curator','researcher'),
        autoIncrement: false,
        primaryKey: false,
        allowNull: true
      },
    }, {
      tableName: 'User',
      timestamps: false,
      underscored: false,

      classMethods: {
        associate: function associate(models) {    
          User.belongsTo(models.Access, {
            foreignKey: 'id',              //on User
            targetKey: 'user_id',  //foreign key
          });
          User.belongsTo(models.Person, {
            foreignKey: 'email',              //on User
            targetKey: 'email',  //foreign key
          });
        }
      },
    });

    return User;
  };