
//alternative solution create a temp table https://stackoverflow.com/questions/1754674/how-do-i-merge-two-or-more-rows-based-on-their-foreign-key

module.exports={
	"group":{
		_table:"Annotation",
		Sequence:{
			_table:["Mature_miRNA","Mature_miRNA_sequence"],
			_attribute:"sequence"
		}
		
	},
	"attributes":{
		_table:"Annotation",
		'row_attributes':{
			_table:"Mature_miRNA",
			Sequence:{
				_table:"Mature_miRNA_sequence",
				_attribute:"sequence"
			},
			Name:{
				_table:"Mature_miRNA",
				_attribute:"name"
			},
			Accession:{
				_table:"Mature_miRNA",
				_attribute:"accession"
			},
		},
		'targets':{
			_table:"Mature_miRNA",
			list:[{
				_table:'Target',
				_model:{
					_table:'Target',
					id:"",
					target_accession:{_table:"Transcript",_attribute:"accession"},
					target_description:"",
					score:"",
					expectation:""
				}
			}]
		}
	},
	"header":{
		_table:"Assay",
		"assayName":"name",
	},
	'grouping_attributes':{
		_table:"./",
		"raw":"",
		"cpm":"",
	},
	metadata:{
		_table:"./",
		row:{
			_table:"./",
			assayId:{_table:"Assay",_attribute:"id"},
			sequnce:{_table:['Annotation',"Mature_miRNA","Mature_miRNA_sequence"],_attribute:"sequence"}
		},
		cell:{
			_table:"./",
			id:"",
			assayId:{_table:"Assay",_attribute:"id"},
		}
	}
}