module.exports={
	"group":{
		_table:"Annotation",
		Sequence:{
			_table:["Mature_miRNA","Mature_miRNA_sequence"],
			_attribute:"sequence"
		}
		
	},
	"attributes":{
		_table:"Annotation",
		'row_attributes':{
			_table:"Mature_miRNA",
			Sequence:{
				_table:"Mature_miRNA_sequence",
				_attribute:"sequence"
			},
			Name:{
				_table:"Mature_miRNA",
				_attribute:"name"
			},
			Accession:{
				_table:"Mature_miRNA",
				_attribute:"accession"
			},
		},
		'targets':{
			_table:"Mature_miRNA",
			Target_Accession:{
				_table:['Target','Transcript'],
				_attribute:"accession"
			},
			Target_Description:{
				_table:'Target',
				_attribute:"target_description"
			}
		}
	},
	"header":{
		_table:"Assay",
		"assayName":"name",
	},
	'grouping_attributes':{
		_table:"./",
		"raw":"",
		"cpm":"",
	},
	metadata:{
		_table:"./",
		row:{
			_table:"Assay",
			assayId:"id"		
		},
		cell:{
			_table:"./",
			id:"",
			assayId:{_table:"Assay",_attribute:"id"},
		}
	}
}