module.exports={
	"mature_miRNA_id":"id",
	"mature_accession":"accession",
	"mature_description":"description",
	"pre_sequence":{"_table":["Mature_has_Pre","Pre_miRNA","Pre_miRNA_sequence"],"_attribute":"sequence"},
	"precursor":{
		"_table":["Mature_has_Pre","Pre_miRNA"],
		"id":"",
		"name":"",
		"accession":"",
		"description":"",
	},
	"Mature_Feature":{
		"_table":["Mature_has_Pre","Feature"],
		"name":"",
		"source":"",
		"type":"",
		"start":"",
		"end":"",
		"score":"",
		"strand":"",
		"phase":""
	}
}