module.exports={
	"id":"",
	"accession":"",
	"name":"",
	"description":"",
	"arm":"",
	"sequence":{_table:"Mature_miRNA_sequence",_attribute:"sequence"},
	"Organism":{
		"_table":["Feature","Genome","Organism"],
		"id":"ncbi_taxon_id",
		"genus":"",
		"specific_name":"",
		"common_name":"",
		"ncbi_taxon_id":""
	}
}